server:
  port: 5001
spring:
  jpa:
  #    postgres
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  #    mysql
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: update
  datasource:
# postgres
    url: jdbc:postgresql://localhost:5432/bankAccount
    username: postgres
    password: techbankNet
# mysql
#  url: jdbc:mysql://localhost:3306/bankAccount?createDatabaseIfNotExist=true
#    username: root
#    password: techbankNet
  kafka:
    listener:
      ack-mode: manual_immediate
    consumer:
      bootstrap-servers: localhost:9092
      group-id: bankaccConsumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
#logging:
#  level:
#    org.springframework.web: DEBUG
#    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
#    org: INFO